#!/usr/bin/env python
"""Push a training session to Kaggle from your own machine.

    python kaggle_launch.py --user evanwang810 --preset medium --hours 8.5 \
        --data evanwang810/fineweb-edu-tokens

Generates the kernel script and its metadata, then hands both to the `kaggle`
CLI. Credentials are never read or printed here: the CLI picks them up from
~/.kaggle/kaggle.json or KAGGLE_USERNAME / KAGGLE_KEY the same way it does for
any other command, so this script works without ever seeing the token.

Set it up once, if you have not already:

    pip install kaggle
    # download kaggle.json from kaggle.com -> Settings -> API -> Create New Token
    # put it at ~/.kaggle/kaggle.json, or %USERPROFILE% then .kaggle on Windows

A session is one committed kernel run. For a multi session model, run this once
per session, passing the previous session's kernel to --resume so its output
mounts as an input and kaggle_run.sh finds the checkpoint.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = "https://github.com/evanwang810/llm67m"

# From the Kaggle CLI's own docs. Only the shapes this project can actually use.
MACHINES = {
    "tpu": "Tpu1VmV38",
    "t4x2": "NvidiaTeslaT4",
    "p100": "NvidiaTeslaP100",
    "none": None,
}

SCRIPT = '''# generated by kaggle_launch.py, do not edit here
import subprocess, sys

subprocess.run(["rm", "-rf", "/kaggle/working/code"], check=True)
subprocess.run(["git", "clone", "-q", "{repo}", "/kaggle/working/code"], check=True)

cmd = {cmd!r}
env = {env!r}
print("running:", " ".join(f"{{k}}={{v}}" for k, v in env.items()), " ".join(cmd), flush=True)

import os
os.environ.update(env)
rc = subprocess.run(cmd, cwd="/kaggle/working/code").returncode
sys.exit(rc)
'''


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--user", default=os.environ.get("KAGGLE_USERNAME", ""),
                   help="your Kaggle username, or set KAGGLE_USERNAME")
    p.add_argument("--slug", default="", help="kernel slug, default llm67m-<preset>-s<n>")
    p.add_argument("--session", type=int, default=1, help="which session this is, for the slug")
    p.add_argument("--device", choices=sorted(MACHINES), default="tpu")
    p.add_argument("--preset", default="medium")
    p.add_argument("--hours", type=float, default=8.5)
    p.add_argument("--tokens", default="7.5e9")
    p.add_argument("--sft-hours", type=float, default=0.0,
                   help="instruction tune after training, 0 to skip")
    p.add_argument("--sft-data", default="chat")
    p.add_argument("--data", default="", help="tokens dataset, user/slug")
    p.add_argument("--resume", default="",
                   help="previous session's kernel, user/slug, mounted for its checkpoint")
    p.add_argument("--public", action="store_true")
    p.add_argument("--dry-run", action="store_true", help="write the folder, do not push")
    return p.parse_args()


def build_payload(args, out: Path) -> tuple[Path, str]:
    slug = args.slug or f"llm67m-{args.preset}-s{args.session}"
    kernel_id = f"{args.user}/{slug}"

    cmd = ["bash", "kaggle_run.sh", str(args.hours), args.preset, args.tokens]
    env = {"DEVICE": args.device, "MONITOR": "1"}
    if args.sft_hours > 0:
        env["SFT_HOURS"] = str(args.sft_hours)
        env["SFT_DATA"] = args.sft_data
    # Nothing to set for a resume: pick_resume_checkpoint globs /kaggle/input
    # through default_search_dirs and takes the newest full checkpoint, so
    # mounting the previous kernel below is the whole of the wiring.

    (out / "run.py").write_text(
        SCRIPT.format(repo=REPO, cmd=cmd, env=env), encoding="utf-8")

    meta = {
        "id": kernel_id,
        "title": slug,
        "code_file": "run.py",
        "language": "python",
        "kernel_type": "script",
        "is_private": not args.public,
        "enable_internet": True,
        "enable_gpu": args.device in ("t4x2", "p100"),
        "dataset_sources": [args.data] if args.data else [],
        "kernel_sources": [args.resume] if args.resume else [],
        "competition_sources": [],
        "model_sources": [],
    }
    if MACHINES[args.device]:
        meta["machine_shape"] = MACHINES[args.device]
    (out / "kernel-metadata.json").write_text(json.dumps(meta, indent=2), encoding="utf-8")
    return out, kernel_id


def main() -> None:
    args = parse_args()
    if not args.user:
        raise SystemExit("pass --user or set KAGGLE_USERNAME")

    with tempfile.TemporaryDirectory() as td:
        out, kernel_id = build_payload(args, Path(td))
        print((out / "kernel-metadata.json").read_text(encoding="utf-8"))
        print((out / "run.py").read_text(encoding="utf-8"))
        if args.dry_run:
            keep = Path.cwd() / "kernel_payload"
            keep.mkdir(exist_ok=True)
            for f in out.iterdir():
                (keep / f.name).write_bytes(f.read_bytes())
            print(f"dry run, payload written to {keep}")
            return

        try:
            r = subprocess.run(["kaggle", "kernels", "push", "-p", str(out)],
                               capture_output=True, text=True)
        except FileNotFoundError:
            raise SystemExit("the kaggle CLI is not installed. pip install kaggle")
        sys.stdout.write(r.stdout)
        sys.stderr.write(r.stderr)
        if r.returncode != 0:
            raise SystemExit(r.returncode)

    print(f"\nhttps://www.kaggle.com/code/{kernel_id}")
    print(f"kaggle kernels status {kernel_id}")
    print(f"kaggle kernels output {kernel_id} -p ./out")


if __name__ == "__main__":
    main()
